<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Carubbi.LayoutTemplateEngine.Interfaces\Carubbi.LayoutTemplateEngine.Interfaces.csproj" />
    <ProjectReference Include="..\..\src\Carubbi.LayoutTemplateEngine.Razor\Carubbi.LayoutTemplateEngine.Razor.csproj" />
    <ProjectReference Include="..\..\src\Carubbi.LayoutTemplateEngine.NVelocity\Carubbi.LayoutTemplateEngine.NVelocity.csproj" />
    <ProjectReference Include="..\..\src\Carubbi.LayoutTemplateEngine.Scriban\Carubbi.LayoutTemplateEngine.Scriban.csproj" />
  </ItemGroup>

</Project>
